# Generated by Django 3.2.6 on 2021-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210815_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
