# Generated by Django 3.2.6 on 2021-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210815_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
